- name: Activate EPEL
  dnf: 
    name: epel-release
  tags: &TAGS
    - docker
- name: Add repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/
  tags: *TAGS
- name: Install app
  dnf: 
    name: 
      - docker-ce
      - python36
  tags: *TAGS

- name: docker-compose | Create venv
  command: python36 -m venv --copies /opt/docker-compose
  args:
    creates: /opt/docker-compose/bin/python
  tags: *TAGS
- name: docker-compose | Install app
  command: /opt/docker-compose/bin/pip install docker-compose
  args:
    creates: /opt/docker-compose/bin/docker-compose
  tags: *TAGS