- name: Activate EPEL
  yum: 
    name: epel-release
  tags:
    - docker
- name: Install requirements
  yum:
    name: "{{ item }}"
  with_items:
    - python36
  tags:
    - docker
- name: Add repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/
  tags:
    - docker
- name: Install app
  yum: 
    name: "{{ item }}"
  with_items:
    - docker-ce
  tags:
    - docker
- name: docker-compose | Create venv
  command: python3.6 -m venv --copies /opt/docker-compose
  args:
    creates: /opt/docker-compose/bin/python
  tags:
    - docker