- name: 'Docker | Add repository'
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/
  tags:
    - docker
- name: 'Docker | Install docker'
  yum: 
    name: "{{ item }}"
  with_items:
    - docker-ce
  tags:
    - docker
- name: 'Docker | Compose | Install requirements'
  yum:
    name: "{{ item }}"
  with_items:
    - python36
  tags:
    - docker
- name: 'Docker | Compose | Create venv'
  command: python3.6 -m venv --copies /opt/docker-compose
  args:
    creates: /opt/docker-compose/bin/python
  tags:
    - docker
- name: 'Docker | Compose | Install compose'
  pip:
    name: "{{ item }}"
    virtualenv: /opt/docker-compose
  with_items:
    - docker-compose
  tags:
    - docker
- name: 'Docker | Compose | Create links'
  file:
    src: /opt/docker-compose/bin/docker-compose
    dest: /usr/local/bin/docker-compose
    state: link
  tags:
    - docker
- name: 'Docker | Compose | Docker as user'
  user:
    name: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    groups: docker
    append: yes
  tags:
    - docker
- name: 'Docker | User | Create folders'
  file:
    path: /docker/apps/
    state: directory
  tags:
    - docker
- name: 'Docker | User | Create links'
  file:
    src: /var/lib/docker
    dest: /docker/data
    state: link
    force: yes
  tags:
    - docker
- name: 'Docker | User | Allow unprivileged access'
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  tags:
    - docker
