- name: 'Network | Extend facts'
  set_fact: 
    full_net: "{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.netmask }}"
- name: 'Network | Create folders'
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - /etc/systemd/network
    - /srv/systemd/network
  tags:
    - network
- name: 'Network | Install dependencies'
  yum: 
    name: "{{ item }}"
  with_items:
    - systemd-networkd
    - systemd-resolved
  tags:
    - network
- name: 'Network | Generate service script'
  template:
    src: files/network/physical.network.j2
    dest: /srv/systemd/network/physical.network
  tags:
    - network
- name: 'Network | Enable network scripts'
  copy:
    src: '/srv/systemd/network/physical.network'
    dest: '/etc/systemd/network/physical.network'
    remote_src: yes
  tags:
    - network
- name: 'Network | Change network services autostart'
  systemd:
    name: "{{item.name}}"
    enabled: "{{item.enabled}}"
  with_items:
    - { name: network, enabled: false }
    - { name: NetworkManager, enabled: false }
    - { name: systemd-networkd, enabled: true }
    - { name: systemd-resolved, enabled: true }
  tags:
    - network
- name: 'Network | Start services'
  systemd:
    name: "{{ item }}"
    state: started
  with_items:
    - systemd-networkd
    - systemd-resolved
  tags:
    - network
- name: 'Network | DNS | Delete resolv.conf'
  file:
    name: /etc/resolv.conf
    state: absent
  tags:
    - network
- name: 'Network | DNS | Link resolv.conf to systemd-resolved'
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  tags:
    - network