- name: Create project folders
  tags: &tags
    - always
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/docker
    - /docker/apps
    - /docker/volumes
- name: Create project links
  tags: *tags
  file:
    src: /var/lib/docker
    dest: /docker/data
    state: link
    force: yes

- name: "Configure unprivilege access for {{ ansible_user }}"
  tags: *tags
  user:
    name: "{{ item }}"
    groups:
      - docker
    append: yes
  when: docker_access
  with_items:
    - "{{ ansible_user }}"

- name: Start docker at boot
  tags: *tags
  systemd:
    name: docker
    enabled: yes
    state: started
  when: docker_autostart
- name: Create docker daemon custom configuration
  tags: *tags
  template:
    src: "docker/{{ docker_daemon_config_file }}"
    dest: "/etc/docker/daemon.json"
  when: docker_daemon_config
- name: Docker authorization
  tags: *tags
  command: docker login -u {{ item.user }} -p {{ item.password }} {{ item.registry }}
  loop: "{{ docker_auth_registries }}"
  loop_control:
    label: "{{ item.registry }}"
  when: docker_auth
  become: "{{ ansible_user }}"
