- name: docker | Activate EPEL
  tags: &tags
    - always
  yum:
    name: epel-release
- name: docker | Add repository
  tags: *tags
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/
- name: docker | Install app
  tags: *tags
  yum:
    name:
      - docker-ce
      - python-pip
- name: docker | Install SDK
  tags: *tags
  pip:
    name: docker
  when: docker_sdk
