- name: docker-compose | Install SDK
  tags: &tags
    - always
  pip:
    name: docker-compose
  when: docker_sdk
- name: docker-compose | Remove SDK app link
  tags: *tags
  file:
    path: /usr/local/bin/docker-compose
    state: absent
  when: docker_sdk
- name: docker-compose | Create links
  tags: *tags
  file:
    src: /opt/docker-compose/docker-compose
    dest: /usr/local/bin/docker-compose
    state: link
