- name: docker | Install requirements
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
  tags: &TAGS
    - docker
- name: docker | Add GPG key
  apt_key:
    id: 0EBFCD88
    url: "https://download.docker.com/linux/{{ ansible_os_family | lower }}/gpg"
    state: present
  tags: *TAGS
- name: docker | Add latest stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
  tags: *TAGS
- name: docker | Install app
  apt:
    name: docker-ce
  tags: *TAGS
- name: docker | Install pip
  apt: 
    name: python3-pip
  tags: *TAGS