- name: docker | Install requirements
  apt:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
  tags: &TAGS
    - docker
- name: docker | Add GPG key
  apt_key:
    id: 0EBFCD88
    url: "https://download.docker.com/linux/{{ ansible_os_family | lower }}/gpg"
    state: present
  tags: *TAGS
- name: docker | Add latest stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename }} stable"
    state: present
  tags: *TAGS
- name: docker | Install app
  apt:
    name: "{{ item }}"
  with_items:
    - docker-ce
  tags: *TAGS