- name: docker | Setup on CentOS
  include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'
  tags: &TAGS
    - docker
- name: docker | Setup on Debian
  include_tasks: debian.yml
  when: ansible_distribution == 'Debian'
  tags: *TAGS
- name: docker | Setup on Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: *TAGS

- name: Create project folders
  file:
    path: /docker/apps/
    state: directory
  tags: *TAGS
- name: Create project links
  file:
    src: /var/lib/docker
    dest: /docker/data
    state: link
    force: yes
  tags: *TAGS

- name: "Configure unprivilege access for {{ ansible_user }}"
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items:
    - "{{ ansible_user }}"
  tags: *TAGS

- name: Start docker at boot
  systemd:
    name: docker
    enabled: yes
    state: started
  when: docker_autostart
  tags: *TAGS

- name: Create docker daemon custom configuration
  template:
    src: "docker/{{ docker_daemon_config_file }}"
    dest: "/etc/docker/daemon.json"
  when: docker_daemon_config
  tags: *TAGS
