- include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'
  tags: &TAGS
    - docker
- include_tasks: debian.yml
  when: ansible_distribution == 'Debian'
  tags: *TAGS
- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: *TAGS
- name: Create project folders
  file:
    path: /docker/apps/
    state: directory
  tags: *TAGS
- name: Create project links
  file:
    src: /var/lib/docker
    dest: /docker/data
    state: link
    force: yes
  tags: *TAGS

- name: "Configure unprivilege access for {{ ansible_user }}"
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items:
    - "{{ ansible_user }}"
  tags: *TAGS